version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    environment:
      # API密钥配置
      - API_KEY=${API_KEY:-${OPENAI_API_KEY}}
      
      # 存储配置
      - CHROMA_DB_PATH=/app/data/chroma_db
      - UPLOAD_DIR=/app/data/uploads
      
      # 安全配置
      - DEBUG=False
      
      # CORS配置（生产环境需要指定具体域名）
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:8501}
      - ALLOWED_METHODS=${ALLOWED_METHODS:-GET,POST,DELETE}
      - ALLOWED_HEADERS=${ALLOWED_HEADERS:-Content-Type,Authorization}
    env_file:
      - ../.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app_data:
    driver: local

networks:
  default:
    driver: bridge