#!/bin/bash
set -euo pipefail

API_KEY="${API_KEY:-${OPENAI_API_KEY:-${DEEPSEEK_API_KEY:-}}}"
EMBEDDING_API_KEY="${EMBEDDING_API_KEY:-}"
JWT_SECRET="${JWT_SECRET:-}"
ADMIN_PASSWORD_HASH="${ADMIN_PASSWORD_HASH:-}"

ensure_directory() {
    local path="$1"
    if [ -e "$path" ] && [ ! -d "$path" ]; then
        echo "ERROR: path exists but is not a directory: $path"
        exit 1
    fi
    mkdir -p "$path"
}

write_secret() {
    local path="$1"
    local value="$2"
    local label="$3"

    if [ -z "$value" ]; then
        echo "ERROR: $label cannot be empty"
        exit 1
    fi

    printf '%s' "$value" > "$path"
    chmod 600 "$path"
    echo "Created $label: $path"
}

prompt_secret_if_empty() {
    local var_name="$1"
    local prompt="$2"
    local current_value="${!var_name:-}"

    if [ -z "$current_value" ]; then
        read -r -s -p "$prompt: " current_value
        echo ""
    fi

    printf -v "$var_name" '%s' "$current_value"
}

prompt_text_if_empty() {
    local var_name="$1"
    local prompt="$2"
    local current_value="${!var_name:-}"

    if [ -z "$current_value" ]; then
        read -r -p "$prompt: " current_value
    fi

    printf -v "$var_name" '%s' "$current_value"
}

echo "Production secrets setup wizard"
echo ""

if ! command -v docker >/dev/null 2>&1; then
    echo "WARNING: Docker is not installed or not in PATH; continuing to create secret files"
fi

ensure_directory secrets
ensure_directory secrets/openai_api_key
ensure_directory secrets/jwt_secret
ensure_directory secrets/admin_password_hash

prompt_secret_if_empty API_KEY "Enter DeepSeek/LLM API Key"
prompt_secret_if_empty EMBEDDING_API_KEY "Enter Embedding API Key"

if [ -z "$JWT_SECRET" ]; then
    if command -v openssl >/dev/null 2>&1; then
        JWT_SECRET="$(openssl rand -hex 32)"
        echo "Generated JWT Secret"
    else
        prompt_secret_if_empty JWT_SECRET "Enter JWT Secret"
    fi
fi

prompt_text_if_empty ADMIN_PASSWORD_HASH "Enter admin password hash generated by python scripts/generate_admin_hash.py"
ADMIN_PASSWORD_HASH="${ADMIN_PASSWORD_HASH#ADMIN_PASSWORD_HASH=}"

write_secret secrets/openai_api_key/deepseek_api_key "$API_KEY" "LLM API Key"
write_secret secrets/embedding_api_key "$EMBEDDING_API_KEY" "Embedding API Key"
write_secret secrets/jwt_secret/token_secret "$JWT_SECRET" "JWT Secret"
write_secret secrets/admin_password_hash/password_hash "$ADMIN_PASSWORD_HASH" "Admin Password Hash"

chmod 700 secrets secrets/openai_api_key secrets/jwt_secret secrets/admin_password_hash

echo ""
echo "File permissions set to 600; secret directory permissions set to 700"
echo ""
echo "Production will read secrets from:"
echo "   /run/secrets/openai_api_key/deepseek_api_key"
echo "   /run/secrets/embedding_api_key"
echo "   /run/secrets/jwt_secret/token_secret"
echo "   /run/secrets/admin_password_hash/password_hash"
echo ""
echo "Important:"
echo "   - Do not commit real files under secrets/"
echo "   - Store ADMIN_PASSWORD_HASH, not the plaintext password"
echo "   - Back up and rotate production secrets regularly"
