name: Test Only

on:
  workflow_dispatch:
  schedule:
    # 每天凌晨2点运行测试
    - cron: '0 2 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create test directories
      run: |
        mkdir -p data/uploads data/chroma_db logs

    - name: Run tests with coverage
      env:
        OPENAI_API_KEY: 'test-key'
        PYTHONPATH: .
      run: |
        pytest tests/ --cov=app --cov-report=term-missing -v

    - name: Test Docker builds
      run: |
        docker build -f docker/Dockerfile.backend -t rag-backend:test .
        docker build -f docker/Dockerfile.frontend -t rag-frontend:test .

    - name: Test Docker Compose
      run: |
        echo "OPENAI_API_KEY=test-key" > .env
        docker-compose -f docker/docker-compose.yml config